# Base configs
baseurl: "https://charlottephotos.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Vinay"
subtitle: "Awesome"
author: "Vinay"
header:
 title: "Photography"
 subtitle: "by Vinay"
footer:
 name: "Hey there, my name is Vinay"
 bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/charlottephotos/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com"
  twitter: "https://www.twitter.com"
  instagram: "https://www.instagram.com"
  dribbble: "https://dribbble.com"
  linkedin: "https://in.linkedin.com"
  github: "https://www.github.com"
